# Generated by Django 5.2.8 on 2025-12-01 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="personality",
            field=models.CharField(
                choices=[
                    ("calm", "Calm"),
                    ("playful", "Playful"),
                    ("curious", "Curious"),
                    ("gentle", "Gentle"),
                    ("energetic", "Energetic"),
                ],
                default="calm",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MatchingPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "looking_for",
                    models.CharField(
                        choices=[
                            ("playmate", "Playmate"),
                            ("adoption", "Adoption"),
                            ("breeding", "Breeding"),
                            ("any", "Any"),
                        ],
                        default="playmate",
                        max_length=20,
                    ),
                ),
                ("preferred_personalities", models.JSONField(blank=True, default=list)),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                ("preferred_sizes", models.JSONField(blank=True, default=list)),
                ("max_distance", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_preferences",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching Preferences",
                "verbose_name_plural": "Matching Preferences",
                "db_table": "matching_preferences",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pet1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_pet1",
                        to="pets.pet",
                    ),
                ),
                (
                    "pet2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_pet2",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "matches",
                "unique_together": {("pet1", "pet2")},
            },
        ),
        migrations.CreateModel(
            name="Swipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("super_like", "Super Like"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "swiped_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes_received",
                        to="pets.pet",
                    ),
                ),
                (
                    "swiper_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipes_made",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Swipe",
                "verbose_name_plural": "Swipes",
                "db_table": "swipes",
                "unique_together": {("swiper_pet", "swiped_pet")},
            },
        ),
    ]
